# Generated by Django 3.1.7 on 2021-10-09 11:34

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_remove_flat_owner_pure_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='owner_pure_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default=None, max_length=20, region=None, verbose_name='Нормализированный номер владельца'),
            preserve_default=False,
        ),
    ]
