# Generated by Django 3.1.7 on 2021-10-10 06:08

from django.db import migrations


def fill_owners_flats(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for owner in Owner.objects.all():
        flats = Flat.objects.filter(owner=owner.name)
        owner.flats.set(flats)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0017_auto_20211010_0849'),
    ]

    operations = [
        migrations.RunPython(fill_owners_flats)
    ]
