# Generated by Django 3.1.7 on 2021-10-12 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0020_auto_20211012_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='new_building',
            field=models.NullBooleanField(db_index=True, default=None, verbose_name='Новое ли здание'),
        ),
    ]
